controller:
  motion_law_parameters:
    max_velocity: [0.5, 0.5, 0.5]
    max_acceleration: [0.1, 0.1, 0.1]

  cascade_controllers:
    - name: "joint1"
      inner:
        Kp: 338.13
        Ki: 1521.6
        Kd: 0.0
        filters_on_error_signal:
          - type: NotchFilter
            natural_frequency: 600
            zeros_damping: 0.04
            poles_damping: 0.9
      outer:
        Kp: 60.59
        Ki: 0.0
        Kd: 0.0
    - name: "joint2"
      inner:
        Kp: 559.66
        Ki: 4477.3
        Kd: 0.0
        filters_on_error_signal:
          - type: NotchFilter
            natural_frequency: 630
            zeros_damping: 0.04
            poles_damping: 0.9
      outer:
        Kp: 110.75
        Ki: 0.0
        Kd: 0.0
    - name: "joint3"
      inner:
        Kp: 325.43
        Ki: 3254.3
        Kd: 0.0
        filters_on_error_signal:
          - type: NotchFilter
            natural_frequency: 640
            zeros_damping: 0.04
            poles_damping: 0.9
      outer:
        Kp: 123.13
        Ki: 0.0
        Kd: 0.0

model_parameters:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
