controller:
  motion_law_parameters:
    max_velocity: [150, 195, 200]
    max_acceleration: [60, 90, 200]

  cascade_controllers:
    - name: "joint1"
      inner:
        Kp: 338.5521
        Ki: 0.0339
        Kd: 0.0
        filters_on_error_signal:
          - type: NotchFilter
            natural_frequency: 600
            zeros_damping: 0.04
            poles_damping: 0.9
      outer:
        Kp: 60.59
        Ki: 0.0
        Kd: 0.0
    - name: "joint2"
      inner:
        Kp: 560.3569
        Ki: 0.0560
        Kd: 0.0
        filters_on_error_signal:
          - type: NotchFilter
            natural_frequency: 630
            zeros_damping: 0.04
            poles_damping: 0.9
      outer:
        Kp: 110.75
        Ki: 0.0
        Kd: 0.0
    - name: "joint3"
      inner:
        Kp: 325.8327
        Ki: 0.0326
        Kd: 0.0
        filters_on_error_signal:
          - type: NotchFilter
            natural_frequency: 640
            zeros_damping: 0.04
            poles_damping: 0.9
      outer:
        Kp: 123.13
        Ki: 0.0
        Kd: 0.0

model_parameters:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
